homebrew_cask_apps:
  - firefox
  - alacritty
  - docker
  - font-jetbrains-mono-nerd-font
  - dotnet-sdk8
  - dotnet-sdk6
  - nikitabobko/tap/aerospace
  - insomnia
  - hyperkey
  - raycast
  - dbeaver-community
  - zen-browser
  - obsidian
  - bitwarden
  - protonvpn
  - reader
  - google-chrome
  - chatgpt
  - nosql-workbench
  - jordanbaird-ice
  - lulu
  - cloudflare-warp
  - postman

homebrew_taps:
  - isen-ng/dotnet-sdk-versions
  - authzed/tap
  - hashicorp/tap
  - kreuzwerker/taps
  - homebrew/command-not-found

homebrew_installed_packages:
  - ripgrep
  - go
  - zellij
  - postgresql@16
  - bitwarden-cli
  - direnv
  - pre-commit
  - authzed/tap/spicedb
  - authzed/tap/zed
  - hashicorp/tap/terraform
  - hashicorp/tap/packer
  - kreuzwerker/taps/m1-terraform-provider-helper
  - terraform-docs
  - k9s
  - awscli
  - pipx
  - iperf3
  - redis
  - protobuf
  - tmux
  - kind
  - fzf
  - git-delta
  - fastfetch
  - navi

neovim_version: v0.10.1

chezmoi_repo: AnhQuanTrl

asdf_plugins:
  - name: nodejs
    repository: https://github.com/asdf-vm/asdf-nodejs.git
    versions:
      - "20.17.0"
    global: "20.17.0"
