---
### Required by aerospace
- name: Group windows by application.
  osx_defaults:
    domain: com.apple.dock
    key: expose-group-apps
    type: bool
    value: true
    state: present

- name: Displays have separate Spaces (false).
  osx_defaults:
    domain: com.apple.spaces
    key: spans-displays
    type: bool
    value: true
    state: present

- name: Autohides the Dock.
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    state: present

### Screenshot
- name: Screenshot default localtion.
  osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "~/Pictures"
    state: present
